version: "3.7"

services:
  iturbo-bot:
    image: ghcr.io/turbocheetah/iturbo:master
    container_name: iturbo-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
