version: '3.3'
services:
    iturbo:
        build:
          context: .
          dockerfile: ./Dockerfile
          args:
            - PM2_ENV=production
            - PM2_PUBLIC_KEY=2iln68dz43vcpg3
            - PM2_SECRET_KEY=i0ny7y1ewq5ehmo
        image: iturbo-discord
        container_name: iTurbo-bot
        restart: always
        depends_on: 
          - iturbo-db
          - iturbo-img-api
        ports: 
          - '5000:5000'
        networks:
          - db
    iturbo-db:
        image: "postgres"
        container_name: iTurbo-db
        environment: 
          - POSTGRES_USER=turbo
          - POSTGRES_PASSWORD=turbodb
          - POSTGRES_DB=miyako
        volumes:
          - ./db:/var/lib/postgresql/data
        # ports: 
        #   - '5432:5432'
        networks:
          - db
    iturbo-img-api:
        container_name: iTurbo-img-api
        ports:
          - '3030:3030'
        image: 'iceemc/img-api:latest'
networks:
  db: