version: '3.3'
services:
    iturbo:
        build: .
        image: iturbo-discord
        container_name: iTurbo
        restart: always
        depends_on: iturbo-db
    iturbo-db:
        image: "postgres"
        environment: 
          - POSTGRES_USER=turbo
          - POSTGRES_PASSWORD=turbodb
          - POSTGRES_DB=miyako
        volumes:
          - ./db:/var/lib/postgresql/data
        ports: 
          - '5432:5432'