version: '3.3'
services:
    iturbo:
        build:
          context: .
          dockerfile: ./Dockerfile
          args:
            - PM2_ENV=production
            - PM2_PUBLIC_KEY=2iln68dz43vcpg3
            - PM2_SECRET_KEY=i0ny7y1ewq5ehmo
        image: iturbo-discord
        container_name: iTurbo-bot
        restart: always
        depends_on: 
          - iturbo-db
          - iturbo-img-api
          - iturbo-lavalink
        ports: 
          - '5000:5000'
        networks:
          - bot
    iturbo-db:
        image: "postgres"
        container_name: iTurbo-db
        restart: always
        environment: 
          - POSTGRES_USER=turbo
          - POSTGRES_PASSWORD=turbodb
          - POSTGRES_DB=miyako
        volumes:
          - ./db:/var/lib/postgresql/data
        # ports: 
        #   - '5432:5432'
        networks:
          - bot
    iturbo-img-api:
        image: 'iceemc/img-api:latest'
        container_name: iTurbo-img-api
        restart: always
        ports:
          - '3030:3030'
        networks:
          - bot 
    iturbo-lavalink:
        image: 'fredboat/lavalink:dev'
        container_name: iTurbo-lavalink
        restart: always
        ports:
          - '2333:2333'
        volumes:
          - ./application.yml:/opt/Lavalink/application.yml
        networks:
          - bot 
networks:
  bot: