version: '3.3'
services:
    iturbo:
        build:
          context: .
          dockerfile: ./Dockerfile
          args:
            - PM2_ENV=production
        image: iturbo-discord
        container_name: iTurbo
        restart: always
        depends_on: 
          - iturbo-db
          - iturbo-img-api
    iturbo-db:
        image: "postgres"
        environment: 
          - POSTGRES_USER=turbo
          - POSTGRES_PASSWORD=turbodb
          - POSTGRES_DB=miyako
        volumes:
          - ./db:/var/lib/postgresql/data
        ports: 
          - '5432:5432'
    iturbo-img-api:
        ports:
          - '3030:3030'
        image: 'iceemc/img-api:latest'